--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/akai/Downloads/test.jpg"

-- Special
background="#0F0F14"
foreground="#e0ded0"
cursor="#e0ded0"

-- Colors
color0="#0F0F14"
color1="#3F3F51"
color2="#912D33"
color3="#AE3234"
color4="#C0393A"
color5="#47958C"
color6="#B9C0A8"
color7="#e0ded0"
color8="#9c9b91"
color9="#3F3F51"
color10="#912D33"
color11="#AE3234"
color12="#C0393A"
color13="#47958C"
color14="#B9C0A8"
color15="#e0ded0"
