# Shell variables
# Generated by 'wal'
wallpaper='/home/akai/Downloads/test.jpg'

# Special
background='#0F0F14'
foreground='#e0ded0'
cursor='#e0ded0'

# Colors
color0='#0F0F14'
color1='#3F3F51'
color2='#912D33'
color3='#AE3234'
color4='#C0393A'
color5='#47958C'
color6='#B9C0A8'
color7='#e0ded0'
color8='#9c9b91'
color9='#3F3F51'
color10='#912D33'
color11='#AE3234'
color12='#C0393A'
color13='#47958C'
color14='#B9C0A8'
color15='#e0ded0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
